
# Syntax highlighting
# markdown:            redcarpet  # github says it is not supported anymore
highlighter:         rouge # pygments is not supported by girhub anymore

# Permalinks
permalink:           /:title

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              en_us

name:                Nodel Films Production

title:
 en:	             a film production company
 ru:	             'test1'

tagline:             'tagline'
description:         'description'
url:                 http://www.nodelfilms.com
rss:                 http://www.nodelfilms.com/feed.xml
baseurl:             '/'
base-url:            '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                assets/img/icon.png # [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:              Elena Nodel
  url:               https://www.nodelfilms.com
  facebook:          lenanodel
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

# enable automatic sitemap generation on Gitub Pages, see https://help.github.com/articles/sitemaps-for-github-pages/
gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
